/** Claude Code 官方工具名（PascalCase）→ 中文展示。与后端 ClaudeCodeToolCatalog 对齐。 */
export const CLAUDE_TOOL_ZH: Record<string, string> = {
  Read: '读取文件',
  Write: '写入文件',
  Edit: '编辑文件',
  NotebookEdit: '编辑 Notebook',
  Glob: '按名查找文件',
  Grep: '内容搜索',
  LSP: '代码智能',
  Bash: '命令行',
  PowerShell: 'PowerShell',
  Monitor: '后台监视命令',
  WebSearch: '网页搜索',
  WebFetch: '抓取网页',
  Agent: '子智能体',
  Task: '子任务（旧）',
  SendMessage: '发送消息给智能体',
  ListAgents: '列出智能体',
  TeamCreate: '创建智能体团队',
  TeamDelete: '删除智能体团队',
  TodoWrite: '任务清单',
  TaskCreate: '创建任务',
  TaskGet: '查看任务',
  TaskList: '任务列表',
  TaskUpdate: '更新任务',
  TaskStop: '停止后台任务',
  TaskOutput: '读取任务输出',
  Skill: '执行技能',
  AskUserQuestion: '向用户提问',
  ToolSearch: '搜索工具',
  EnterPlanMode: '进入计划模式',
  ExitPlanMode: '退出计划模式',
  EnterWorktree: '进入 Worktree',
  ExitWorktree: '退出 Worktree',
  CronCreate: '创建定时任务',
  CronDelete: '删除定时任务',
  CronList: '定时任务列表',
  ScheduleWakeup: '调度唤醒',
  ListMcpResourcesTool: '列出 MCP 资源',
  ReadMcpResourceTool: '读取 MCP 资源',
  WaitForMcpServers: '等待 MCP 连接',
  Artifact: '发布 Artifact',
  Workflow: '运行工作流',
  RemoteTrigger: '远程例程',
  PushNotification: '推送通知',
  SendUserFile: '发送文件给用户',
  ShareOnboardingGuide: '分享入门指南',
  ReportFindings: '报告审查发现',
  EndConversation: '结束会话',
  MultiEdit: '批量编辑',
  BashOutput: '读取命令输出',
}

const CLAUDE_TOOL_ZH_LOWER: Record<string, string> = Object.fromEntries(
  Object.entries(CLAUDE_TOOL_ZH).map(([k, v]) => [k.toLowerCase(), v]),
)

/** 图标种类（与后端 iconKind 对齐） */
export const CLAUDE_TOOL_ICON: Record<string, string> = {
  read: 'extract',
  write: 'file',
  edit: 'code',
  notebookedit: 'code',
  multiedit: 'code',
  glob: 'search',
  grep: 'search',
  lsp: 'code',
  bash: 'terminal',
  bashoutput: 'terminal',
  powershell: 'terminal',
  monitor: 'terminal',
  websearch: 'search',
  webfetch: 'extract',
  agent: 'agent',
  task: 'agent',
  sendmessage: 'agent',
  listagents: 'agent',
  teamcreate: 'agent',
  teamdelete: 'agent',
  todowrite: 'todo',
  taskcreate: 'todo',
  taskget: 'todo',
  tasklist: 'todo',
  taskupdate: 'todo',
  taskstop: 'todo',
  taskoutput: 'todo',
  skill: 'skill',
  askuserquestion: 'ask',
  toolsearch: 'search',
  enterplanmode: 'ask',
  exitplanmode: 'ask',
  enterworktree: 'file',
  exitworktree: 'file',
  croncreate: 'clock',
  crondelete: 'clock',
  cronlist: 'clock',
  schedulewakeup: 'clock',
  listmcpresourcestool: 'gear',
  readmcpresourcetool: 'extract',
  waitformcpservers: 'gear',
  artifact: 'file',
  workflow: 'agent',
  remotetrigger: 'clock',
  pushnotification: 'speak',
  senduserfile: 'file',
  shareonboardingguide: 'social',
  reportfindings: 'code',
  endconversation: 'ask',
}

export function claudeToolLabel(code: string | undefined | null): string | null {
  const raw = (code || '').trim()
  if (!raw) return null
  return CLAUDE_TOOL_ZH[raw] || CLAUDE_TOOL_ZH_LOWER[raw.toLowerCase()] || null
}

export function claudeToolIconKind(code: string | undefined | null): string | null {
  const raw = (code || '').trim()
  if (!raw) return null
  return CLAUDE_TOOL_ICON[raw.toLowerCase()] || null
}
